### ISSUE TITLE
Android "build_sdk.py" script not running properly

### ISSUE THREAD

**Issue by mongoose54** [Itseez/opencv#5561]
Environment: MacOS 10.10, Python: 2.7.10, g++ 4.8, Android NDK 4.8, Android SDK 24.4.0

Step 1:
I followed instructions to build OpenCV SDK from trunk: [http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk](https://github.com/Itseez/opencv/wiki/Building_OpenCV4Android_from_trunk)

Step 2:
Run build_sdk.py from terminal like this:
``python ../opencv/platforms/android/build_sdk.py ../opencv/android_sdk ../opencv``

Output: 
```
=====
===== Building library for armeabi-v7a (arm-linux-androideabi-4.8)
=====
Executing: ['cmake', '-GNinja', "-DCMAKE_TOOLCHAIN_FILE='/Users/alex/Downloads/opencv/platforms/android/android.toolchain.cmake'", '-DWITH_OPENCL=OFF', '-DWITH_CUDA=OFF', '-DWITH_IPP=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_PERF_TESTS=OFF', '-DBUILD_DOCS=OFF', '-DBUILD_ANDROID_EXAMPLES=ON', '-DINSTALL_ANDROID_EXAMPLES=ON', '-DANDROID_STL=gnustl_static', '-DANDROID_NATIVE_API_LEVEL=8', "-DANDROID_ABI='armeabi-v7a with NEON'", '-DWITH_TBB=ON', '-DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.8', '/Users/alex/Downloads/opencv', '-DNDK_CCACHE=ccache', '-DENABLE_PRECOMPILED_HEADERS=OFF', '-DBUILD_TESTS=ON', '-DINSTALL_TESTS=ON']
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file:/Users/alex/Downloads/opencv/android_sdk/o4a/CMakeFiles/2.8.10.2/CMakeCXXCompiler.cmake
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file:/Users/alex/Downloads/opencv/android_sdk/o4a/CMakeFiles/2.8.10.2/CMakeCCompiler.cmake
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "../opencv/platforms/android/build_sdk.py", line 305, in <module>
    builder.build_library(abi, do_install)
  File "../opencv/platforms/android/build_sdk.py", line 143, in build_library
    execute(cmd)
  File "../opencv/platforms/android/build_sdk.py", line 20, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1
```

Cmake and GCC are properly installed and found in PATH. So I modified ``build_sdk.py`` and changed `-GNinja` to `Unix Makefiles` and this is the output:

```
=====
===== Building library for armeabi-v7a (arm-linux-androideabi-4.8)
=====
Executing: ['cmake', 'Unix Makefiles', "-DCMAKE_TOOLCHAIN_FILE='/Users/alex/Downloads/opencv/platforms/android/android.toolchain.cmake'", '-DWITH_OPENCL=OFF', '-DWITH_CUDA=OFF', '-DWITH_IPP=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_PERF_TESTS=OFF', '-DBUILD_DOCS=OFF', '-DBUILD_ANDROID_EXAMPLES=ON', '-DINSTALL_ANDROID_EXAMPLES=ON', '-DANDROID_STL=gnustl_static', '-DANDROID_NATIVE_API_LEVEL=8', "-DANDROID_ABI='armeabi-v7a with NEON'", '-DWITH_TBB=ON', '-DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.8', '/Users/alex/Downloads/opencv', '-DNDK_CCACHE=ccache', '-DENABLE_PRECOMPILED_HEADERS=OFF', '-DBUILD_TESTS=ON', '-DINSTALL_TESTS=ON']
-- Detected version of GNU GCC: 48 (408)
-- Performing Test HAVE_CXX_FSIGNED_CHAR
-- Performing Test HAVE_CXX_FSIGNED_CHAR - Success
-- Performing Test HAVE_C_FSIGNED_CHAR
-- Performing Test HAVE_C_FSIGNED_CHAR - Success
-- Performing Test HAVE_CXX_W
-- Performing Test HAVE_CXX_W - Success
-- Performing Test HAVE_C_W
-- Performing Test HAVE_C_W - Success
-- Performing Test HAVE_CXX_WALL
-- Performing Test HAVE_CXX_WALL - Success
-- Performing Test HAVE_C_WALL
-- Performing Test HAVE_C_WALL - Success
-- Performing Test HAVE_CXX_WERROR_RETURN_TYPE
-- Performing Test HAVE_CXX_WERROR_RETURN_TYPE - Success
-- Performing Test HAVE_C_WERROR_RETURN_TYPE
-- Performing Test HAVE_C_WERROR_RETURN_TYPE - Success
-- Performing Test HAVE_CXX_WERROR_NON_VIRTUAL_DTOR
-- Performing Test HAVE_CXX_WERROR_NON_VIRTUAL_DTOR - Success
-- Performing Test HAVE_C_WERROR_NON_VIRTUAL_DTOR
-- Performing Test HAVE_C_WERROR_NON_VIRTUAL_DTOR - Success
-- Performing Test HAVE_CXX_WERROR_ADDRESS
-- Performing Test HAVE_CXX_WERROR_ADDRESS - Success
-- Performing Test HAVE_C_WERROR_ADDRESS
-- Performing Test HAVE_C_WERROR_ADDRESS - Success
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_CXX_WFORMAT
-- Performing Test HAVE_CXX_WFORMAT - Success
-- Performing Test HAVE_C_WFORMAT
-- Performing Test HAVE_C_WFORMAT - Success
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_CXX_WMISSING_DECLARATIONS
-- Performing Test HAVE_CXX_WMISSING_DECLARATIONS - Success
-- Performing Test HAVE_C_WMISSING_DECLARATIONS
-- Performing Test HAVE_C_WMISSING_DECLARATIONS - Success
-- Performing Test HAVE_CXX_WMISSING_PROTOTYPES
-- Performing Test HAVE_CXX_WMISSING_PROTOTYPES - Failed
-- Performing Test HAVE_C_WMISSING_PROTOTYPES
-- Performing Test HAVE_C_WMISSING_PROTOTYPES - Success
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES - Failed
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES - Success
-- Performing Test HAVE_CXX_WUNDEF
-- Performing Test HAVE_CXX_WUNDEF - Success
-- Performing Test HAVE_C_WUNDEF
-- Performing Test HAVE_C_WUNDEF - Success
-- Performing Test HAVE_CXX_WINIT_SELF
-- Performing Test HAVE_CXX_WINIT_SELF - Success
-- Performing Test HAVE_C_WINIT_SELF
-- Performing Test HAVE_C_WINIT_SELF - Success
-- Performing Test HAVE_CXX_WPOINTER_ARITH
-- Performing Test HAVE_CXX_WPOINTER_ARITH - Success
-- Performing Test HAVE_C_WPOINTER_ARITH
-- Performing Test HAVE_C_WPOINTER_ARITH - Success
-- Performing Test HAVE_CXX_WSHADOW
-- Performing Test HAVE_CXX_WSHADOW - Success
-- Performing Test HAVE_C_WSHADOW
-- Performing Test HAVE_C_WSHADOW - Success
-- Performing Test HAVE_CXX_WSIGN_PROMO
-- Performing Test HAVE_CXX_WSIGN_PROMO - Success
-- Performing Test HAVE_C_WSIGN_PROMO
-- Performing Test HAVE_C_WSIGN_PROMO - Failed
-- Performing Test HAVE_CXX_WNO_NARROWING
-- Performing Test HAVE_CXX_WNO_NARROWING - Success
-- Performing Test HAVE_C_WNO_NARROWING
-- Performing Test HAVE_C_WNO_NARROWING - Success
-- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR
-- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR - Success
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR - Failed
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_CXX_MFPU_NEON
-- Performing Test HAVE_CXX_MFPU_NEON - Success
-- Performing Test HAVE_C_MFPU_NEON
-- Performing Test HAVE_C_MFPU_NEON - Success
-- Performing Test HAVE_CXX_FVISIBILITY_HIDDEN
-- Performing Test HAVE_CXX_FVISIBILITY_HIDDEN - Success
-- Performing Test HAVE_C_FVISIBILITY_HIDDEN
-- Performing Test HAVE_C_FVISIBILITY_HIDDEN - Success
-- Performing Test HAVE_CXX_FVISIBILITY_INLINES_HIDDEN
-- Performing Test HAVE_CXX_FVISIBILITY_INLINES_HIDDEN - Success
-- Performing Test HAVE_C_FVISIBILITY_INLINES_HIDDEN
-- Performing Test HAVE_C_FVISIBILITY_INLINES_HIDDEN - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found ZLIB: /Users/alex/Library/Android/sdk/ndk-bundle/platforms/android-8/arch-arm/usr/lib/libz.so (found suitable version "1.2.3", minimum required is "1.2.3") 
-- Looking for assert.h
-- Looking for assert.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for io.h
-- Looking for io.h - not found
-- Looking for jbg_newlen
-- Looking for jbg_newlen - not found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for search.h
-- Looking for search.h - not found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Performing Test HAVE_C_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_C_WNO_UNUSED_BUT_SET_VARIABLE - Success
-- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES
-- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES - Success
-- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS
-- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS - Success
-- Performing Test HAVE_C_WNO_UNDEF
-- Performing Test HAVE_C_WNO_UNDEF - Success
-- Performing Test HAVE_C_WNO_UNUSED
-- Performing Test HAVE_C_WNO_UNUSED - Success
-- Performing Test HAVE_C_WNO_SIGN_COMPARE
-- Performing Test HAVE_C_WNO_SIGN_COMPARE - Success
-- Performing Test HAVE_C_WNO_CAST_ALIGN
-- Performing Test HAVE_C_WNO_CAST_ALIGN - Success
-- Performing Test HAVE_C_WNO_SHADOW
-- Performing Test HAVE_C_WNO_SHADOW - Success
-- Performing Test HAVE_C_WNO_MAYBE_UNINITIALIZED
-- Performing Test HAVE_C_WNO_MAYBE_UNINITIALIZED - Success
-- Performing Test HAVE_C_WNO_POINTER_TO_INT_CAST
-- Performing Test HAVE_C_WNO_POINTER_TO_INT_CAST - Success
-- Performing Test HAVE_C_WNO_INT_TO_POINTER_CAST
-- Performing Test HAVE_C_WNO_INT_TO_POINTER_CAST - Success
-- Performing Test HAVE_C_WNO_UNUSED_PARAMETER
-- Performing Test HAVE_C_WNO_UNUSED_PARAMETER - Success
-- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS
-- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS - Success
-- Performing Test HAVE_CXX_WNO_UNUSED_PARAMETER
-- Performing Test HAVE_CXX_WNO_UNUSED_PARAMETER - Success
-- Performing Test HAVE_C_WNO_UNUSED_VARIABLE
-- Performing Test HAVE_C_WNO_UNUSED_VARIABLE - Success
-- Performing Test HAVE_C_WNO_UNUSED_FUNCTION
-- Performing Test HAVE_C_WNO_UNUSED_FUNCTION - Success
-- Performing Test HAVE_C_WNO_IMPLICIT_FUNCTION_DECLARATION
-- Performing Test HAVE_C_WNO_IMPLICIT_FUNCTION_DECLARATION - Success
-- Performing Test HAVE_C_WNO_UNINITIALIZED
-- Performing Test HAVE_C_WNO_UNINITIALIZED - Success
-- Performing Test HAVE_C_WNO_UNUSED_BUT_SET_PARAMETER
-- Performing Test HAVE_C_WNO_UNUSED_BUT_SET_PARAMETER - Success
-- Performing Test HAVE_C_WNO_STRICT_OVERFLOW
-- Performing Test HAVE_C_WNO_STRICT_OVERFLOW - Success
-- The ASM compiler identification is GNU
-- Found assembler: /Users/alex/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
-- Looking for semaphore.h
-- Looking for semaphore.h - found
-- Performing Test HAVE_CXX_WNO_SHADOW
-- Performing Test HAVE_CXX_WNO_SHADOW - Success
-- Performing Test HAVE_CXX_WNO_UNUSED
-- Performing Test HAVE_CXX_WNO_UNUSED - Success
-- Performing Test HAVE_CXX_WNO_SIGN_COMPARE
-- Performing Test HAVE_CXX_WNO_SIGN_COMPARE - Success
-- Performing Test HAVE_CXX_WNO_UNDEF
-- Performing Test HAVE_CXX_WNO_UNDEF - Success
-- Performing Test HAVE_CXX_WNO_UNINITIALIZED
-- Performing Test HAVE_CXX_WNO_UNINITIALIZED - Success
-- Performing Test HAVE_CXX_WNO_SWITCH
-- Performing Test HAVE_CXX_WNO_SWITCH - Success
-- Performing Test HAVE_CXX_WNO_PARENTHESES
-- Performing Test HAVE_CXX_WNO_PARENTHESES - Success
-- Performing Test HAVE_CXX_WNO_ARRAY_BOUNDS
-- Performing Test HAVE_CXX_WNO_ARRAY_BOUNDS - Success
-- Performing Test HAVE_CXX_WNO_EXTRA
-- Performing Test HAVE_CXX_WNO_EXTRA - Success
-- Unpacking tbb41_20130116oss_src.tgz to /Users/alex/Downloads/opencv/android_sdk/o4a/3rdparty/tbb/tbb41_20130116oss
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.10", minimum required is "2.7") 
-- Could NOT find PythonInterp: Found unsuitable version "2.7.10", but required is at least "3.4" (found /usr/bin/python)
-- Could NOT find PythonInterp: Found unsuitable version "2.7.10", but required is at least "3.2" (found /usr/bin/python)
-- Found android tool: /Users/alex/Library/Android/sdk/tools/android
-- Could NOT find Matlab (missing:  MATLAB_MEX_SCRIPT MATLAB_INCLUDE_DIRS MATLAB_LIBRARIES MATLAB_LIBRARY_DIRS MATLAB_MEXEXT MATLAB_ARCH MATLAB_BIN) 
-- Assume that non-module dependency is available: z (for module opencv_core)
-- Performing Test HAVE_CXX_WNO_DEPRECATED_DECLARATIONS
-- Performing Test HAVE_CXX_WNO_DEPRECATED_DECLARATIONS - Success
-- Sample example-tutorial-4-opencl is disabled, because ANDROID_OPENCL_SDK is not specified
-- 
-- General configuration for OpenCV 3.0.0-dev =====================================
--   Version control:               3.0.0-613-gb34f0d9-dirty
-- 
--   Platform:
--     Host:                        Darwin 14.5.0 i386
--     Target:                      Linux 1 armv7-a
--     CMake:                       2.8.10.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Release
-- 
--   C/C++:
--     Built as dynamic libs?:      NO
--     C++ Compiler:                /Users/alex/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++  (ver 4.8)
--     C++ flags (Release):         -fexceptions -frtti -fpic -Wno-psabi --sysroot=/Users/alex/Library/Android/sdk/ndk-bundle/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fexceptions -frtti -fpic -Wno-psabi --sysroot=/Users/alex/Library/Android/sdk/ndk-bundle/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -marm -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /Users/alex/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
--     C flags (Release):           -fexceptions -fpic -Wno-psabi --sysroot=/Users/alex/Library/Android/sdk/ndk-bundle/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fexceptions -fpic -Wno-psabi --sysroot=/Users/alex/Library/Android/sdk/ndk-bundle/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -marm -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now 
--     Linker flags (Debug):        -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now 
--     Precompiled headers:         NO
--     Extra dependencies:          dl m log
--     3rdparty dependencies:       tbb
-- 
--   OpenCV modules:
--     To be built:                 hal core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres ts features2d calib3d stitching videostab
--     Disabled:                    world
--     Disabled by dependency:      -
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 viz
-- 
--   Android: 
--     Android ABI:                 armeabi-v7a with NEON
--     STL type:                    gnustl_static
--     Native API level:            android-8
--     SDK target:                  android-20
--     Android NDK:                 /Users/alex/Library/Android/sdk/ndk-bundle (toolchain: arm-linux-androideabi-4.8)
--     android tool:                /Users/alex/Library/Android/sdk/tools/android (Android SDK Tools, revision 24.4.0.)
--     Google Play manager:         NO
--     Android examples:            NO
-- 
--   GUI: 
--     GTK+:                        NO
--     GThread :                    NO
--     GtkGlExt:                    NO
--     OpenGL support:              NO
--     VTK support:                 NO
-- 
--   Media I/O: 
--     ZLib:                        z (ver 1.2.3)
--     JPEG:                        build (ver 90)
--     WEBP:                        build (ver 0.3.1)
--     PNG:                         build (ver 1.5.12)
--     TIFF:                        build (ver 42 - 4.0.2)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     build (ver 1.7.1)
--     GDAL:                        NO
-- 
--   Video I/O:
-- 
--   Parallel framework:            TBB (ver 4.1 interface 6102)
-- 
--   Other third-party libraries:
--     Use IPP:                     NO
--     Use Eigen:                   NO
--     Use Cuda:                    NO
--     Use OpenCL:                  NO
-- 
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.10)
-- 
--   Python 3:
--     Interpreter:                 NO
-- 
--   Python (for build):            /usr/bin/python2.7
-- 
--   Java:
--     ant:                         NO
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Matlab:
--     mex:                         NO
-- 
--   Tests and samples:
--     Tests:                       YES
--     Performance tests:           NO
--     C/C++ Examples:              NO
-- 
--   Install path:                  /Users/alex/Downloads/opencv/android_sdk/o4a/install
-- 
--   cvconfig.h is in:              /Users/alex/Downloads/opencv/android_sdk/o4a
-- -----------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    INSTALL_ANDROID_EXAMPLES


-- Build files have been written to: /Users/alex/Downloads/opencv/android_sdk/o4a
Executing: ['ninja']
Traceback (most recent call last):
  File "../opencv/platforms/android/build_sdk.py", line 305, in <module>
    builder.build_library(abi, do_install)
  File "../opencv/platforms/android/build_sdk.py", line 145, in build_library
    execute(["ninja"])
  File "../opencv/platforms/android/build_sdk.py", line 22, in execute
    raise Fail("Execution failed: %d / %s" % (e.errno, e.strerror))
__main__.Fail: Execution failed: 2 / No such file or directory
```

Am I missing something or is it a bug?

**Comment by alalek** [comment]
These lines
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```
say that [ninja](https://github.com/martine/ninja) is not installed properly.

**Comment by mongoose54** [comment]
@alalek Thanks for pointing out. Re-installing Ninja fixed that error but later on it gives me the following error:

```
Executing: ['ninja', 'opencv_engine']
ninja: error: unknown target 'opencv_engine'
Traceback (most recent call last):
  File "../opencv/platforms/android/build_sdk.py", line 312, in <module>
    builder.build_engine(abi, engdest)
  File "../opencv/platforms/android/build_sdk.py", line 186, in build_engine
    execute(["ninja", "opencv_engine"])
  File "../opencv/platforms/android/build_sdk.py", line 20, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1
```

What is the ``opencv_engine`` and where can I find it? Thanks!

**Comment by mongoose54** [comment]
Never mind I had to install Ant

**Comment by airman00** [comment]
@mongoose54  How did you install Ant? Just  'brew install ant' ?
I'm getting the same opencv_engine as you but ant is already installed via brew

**Comment by mshabunin** [comment]
You need to install Java SDK. Corresponding cmake information block should look like the example below:
```
--   Java:
--     ant:                         /usr/local/bin/ant (ver 1.9.4)
--     Java wrappers:               YES
--     Java tests:                  YES
```

**Comment by airman00** [comment]
I just updated Java SDK via brew (I'm on MacOSX). I still get the same error
    Executing: ['ninja', 'opencv_engine']
    ninja: error: unknown target 'opencv_engine'

My cmake information block looks like this:
    --   Java:
    --     ant:                         /usr/local/bin/ant (ver 1.9.6)
    --     Java wrappers:               YES
    --     Java tests:                  NO

What else can I try to install?

**Comment by mshabunin** [comment]
Please provide full script output log (via pastebin or GitHub snippet).

**Comment by FWStelian** [comment]
Did anyone get this error ?
`Invalid or unsupported command "--silent create lib-project --path /Users/stelian/Downloads/opencv_andy/o4a --target lib_target_sdk_target-NOTFOUND --name OpenCV --package org.opencv"`

**Comment by mongoose54** [comment]
Hi Stelian,

I believe that the latest versions of OpenCV have moved the neural network ingestion to its main distribution making this tutorial obsolete. Hope this helps.

-Alex

**Comment by antonderevyanko** [comment]
I`ve got the same error:
`Adding libraries from /Users/anton/Downloads/OpenCV/gui_build/o4a/lib
Executing: ['ninja', 'opencv_engine']
ninja: error: unknown target 'opencv_engine'
Traceback (most recent call last):
  File "build_sdk.py", line 312, in <module>
    builder.build_engine(abi, engdest)
  File "build_sdk.py", line 191, in build_engine
    execute(["ninja", "opencv_engine"])
  File "build_sdk.py", line 20, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1`
