### ISSUE TITLE
having issues with avcodec_open2() error -22:

### ISSUE THREAD

**Issue by jananiarvind** [Itseez/opencv#5589]
I am trying to save a video by capturing it from web camera.
I use windows 8.1 64 bit OS.
Eclipse luna and javacv, open cv and ffmpeg jars.

While executing the program I get following error:
Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:529)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:288)
	at CameraTest.main(CameraTest.java:34)
Please help me resolve this

**Comment by mshabunin** [comment]
It seems to be a problem in JavaCV library, please try to ask here: https://github.com/bytedeco/javacv
Feel free to reopen the issue if you find additional facts pointing on probem in OpenCV.
