### ISSUE TITLE
BackgroundSubtractorMOG2 apply calls from python causes allocation error

### ISSUE THREAD

**Issue by anthonyk91** [Itseez/opencv#6055]
Error message:
```
  File "(myfile.py)", line 1500, in (some function)
    bgsub.apply(frame)
error: /tmp/opencv-3.1.0/modules/python/src2/cv2.cpp:163: error: (-215) The data should normally be NULL! in function allocate
```

This appears to be a similar bug as [#5667](https://github.com/Itseez/opencv/issues/5667) for knnMatch, however the [fix](https://github.com/Itseez/opencv/pull/6009) for that bug doesn't apply here

The bug seems to be related to an allocate call.  It seems to be avoided for python3 and some people just disable the warning [link](http://stackoverflow.com/questions/32931856/cv2-3-0-0-cv2-flannbasedmatcher-flann-knnmatch-is-throwing-cv2-error), however it would be better to identify the problem (eg for python 2) and prevent it occurring.

**Comment by patricksnape** [comment]
Please provide a short script using the data shipped with OpenCV that replicates your error so that it can be debugged.

**Comment by anthonyk91** [comment]
The following code produces the error on my system:
`
Python 2.7.5 (default, Jul 10 2014, 16:10:08) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2

import cv2
vc = cv2.VideoCapture("768x576.avi")
bgsegm = cv2.createBackgroundSubtractorMOG2()
r,f = vc.read()
bgsegm.apply(f)

OpenCV Error: Assertion failed (The data should normally be NULL!) in allocate, file /tmp/opencv-3.1.0/modules/python/src2/cv2.cpp, line 163
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: /tmp/opencv-3.1.0/modules/python/src2/cv2.cpp:163: error: (-215) The data should normally be NULL! in function allocate
`
I'm running it on CentOS 6, when I run it on a separate CentOS 7 system the error isn't produced.  (The CentOS 7 system is also using python 2.7.5, with GCC 4.8.5 (i'm not sure if this is used)).  The error first appeared after changing from OpenCV 3.0.0 to 3.1.  It seems related to the system config somehow but i'm not sure what.

**Comment by patricksnape** [comment]
I can't replicate this error on my Ubuntu, Windows or OSX machines for either Python 2.7.11 or 3.5. Did you compile OpenCV 3.1 yourself?

**Comment by anatolix** [comment]
I have same error. I compiled opencv 3.1 myself, OSX, Python 3.5. cmake output attached.
[cmake.txt](https://github.com/Itseez/opencv/files/120955/cmake.txt)

**Comment by patricksnape** [comment]
Thanks @anatolix - it seems like the issue is related to OpenCL support. I can't replicate the error with OpenCL off, but with OpenCL on I get a segmentation fault. Given the other error I fixed, I feel like it has to do with [this line](https://github.com/Itseez/opencv/blob/3942b1f36261b196a264eb35c996222848fe3c93/modules/video/src/bgfg_gaussmix2.cpp#L849), which I'm guessing should be looking for a `UMat` in the case of OpenCV support.

**Comment by anthonyk91** [comment]
I can confirm that after editing CMakeCache.txt to set WITH_OPENCL.. flags to OFF and rebuilding, the error disappears.

**Comment by bw4sz** [comment]
Same error here. Python 2.7, most recent opencv windows (10) binary. Anyway to get around this without recompiling with cmake? Just want to check before i head down that road. I can't comment out a line (other offered solution) without recompiling, correct?

**Comment by patricksnape** [comment]
@bw4sz Seems like binaries compiled with OpenCL support are broken - so if the latest Windows binaries have OpenCL support you will still see this error (it is independent of Python version it seems).

**Comment by bw4sz** [comment]
Sorry, rebuilt with opencl support off, same error for cv2.createBackgroundSubtractorMOG2 when applied to a frame. cmake log attached. I did also build with contrib libraries? Windows 10, Python 2.7, opencv and contrib cloned this afternoon.

[CMakeVars.txt](https://github.com/Itseez/opencv/files/138849/CMakeVars.txt)


    error: C:\builds\master_PackSlaveAddon-win32-vc12-static\opencv\modules\python\src2\cv2.cpp:163: error: (-215) The data should normally be NULL! in function NumpyAllocator::allocate

**Comment by Dikay900** [comment]
No you have to build OpenCV yourself since all releases are built with OPENCL ON in favor of the T-API.
There is currently no support for the T-API in python at all.
Maybe we will see T-API support in the near future but for now this is the way to go for the python bindings.

**Comment by bw4sz** [comment]
Confirming building from source worked. Thanks.

**Comment by PolarNick239** [comment]
The simpler **workaround** that could work is to disable OpenCL in runtime by `cv2.ocl.setUseOpenCL(False)` (https://github.com/Itseez/opencv/issues/6081#issuecomment-198287324)

**Comment by gsideaf** [comment]
Any word on this issue getting fixed?  Would be nice to be able to use OpenCL acceleration with MOG2? Thanks
