### ISSUE TITLE
buildPyramid segfaults  with Clang

### ISSUE THREAD

**Issue by lvv** [Itseez/opencv#6092]
Following test program segfaults if compiled with Clang:

#include <opencv2/opencv.hpp>
#include <vector>

int main() {
        cv::Mat  I(1000,1000,CV_8UC1);
        std::vector<cv::Mat>  P; 
        cv::buildPyramid(I, P, 30);
        return P.size();
}

clang --version
Ubuntu clang version 3.6.2-1 (tags/RELEASE_362/final)

cat /etc/os-release 
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"

OpenCV github at tag 3.1.0
compile config: 
 cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local  -D BUILD_EXAMPLES=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_CUDA=OFF -D WITH_IPP=OFF  .

**Comment by alalek** [comment]
1) Stack trace is required
2) Try configure with `-DWITH_OPENCL=OFF` option or add `cv::ocl::setUseOpenCL(false)` into `main()`

**Comment by lvv** [comment]
I wanted to add that segfaults are not always happening.  In my program, that I develop, buildPyramid() leaves pyramid uninitialized (when using clang). 

Setting ocl::setUseOpenCL(false) or using build with OPENCL=OFF  - does not make any visible change in behavior, it still segfaults.

This is trace of test program  with OPENCL=OFF:

`Starting program: /home/lvv/p/cv/people_counter/t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffa0cfa700 (LWP 19978)]
   
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff78a354b in cv::Mat::Mat (this=0x60, m=...) at /home/tr/opencv.lvv-git/modules/core/include/opencv2/core/mat.inl.hpp:389
389           u(m.u), size(&rows)
(gdb) bt
#0  0x00007ffff78a354b in cv::Mat::Mat (this=0x60, m=...) at /home/tr/opencv.lvv-git/modules/core/include/opencv2/core/mat.inl.hpp:389
#1  0x00007ffff6cc5f0a in std::_Construct<cv::Mat, cv::Mat> (__p=0x60, __value=...) at /usr/include/c++/4.9/bits/stl_construct.h:83
#2  0x00007ffff6cc5a2e in std::__uninitialized_fill_n<false>::__uninit_fill_n<cv::Mat*, unsigned long, cv::Mat> (__first=0x0, __n=30, __x=...)
    at /usr/include/c++/4.9/bits/stl_uninitialized.h:202
#3  0x00007ffff6cc5290 in std::uninitialized_fill_n<cv::Mat*, unsigned long, cv::Mat> (__first=0x0, __n=31, __x=...)
    at /usr/include/c++/4.9/bits/stl_uninitialized.h:244
#4  0x00007ffff6cc4bd3 in std::__uninitialized_fill_n_a<cv::Mat*, unsigned long, cv::Mat, cv::Mat> (__first=0x0, __n=31, __x=...)
    at /usr/include/c++/4.9/bits/stl_uninitialized.h:355
#5  0x00007ffff6cf71fe in std::vector<cv::Mat, std::allocator<cv::Mat> >::_M_fill_insert (this=0x7fffffffd5d8,
    __position=<error reading variable: Cannot access memory at address 0x0>, __n=31, __x=...) at /usr/include/c++/4.9/bits/vector.tcc:474
#6  0x00007ffff6cf3452 in std::vector<cv::Mat, std::allocator<cv::Mat> >::insert (this=0x7fffffffd5d8,
    __position=<error reading variable: Cannot access memory at address 0x0>, __n=31, __x=...) at /usr/include/c++/4.9/bits/stl_vector.h:1073
#7  0x00007ffff6cede50 in std::vector<cv::Mat, std::allocator<cv::Mat> >::resize (this=0x7fffffffd5d8, __new_size=31, __x=...)
    at /usr/include/c++/4.9/bits/stl_vector.h:716
#8  0x00007fffdc45aae4 in cv::_OutputArray::create (this=0x7fffffffd598, d=2, sizes=0x7fffffffd3d0, mtype=0, i=-1, allowTransposed=false,
    fixedDepthMask=0) at /home/tr/opencv.lvv-git/modules/core/src/matrix.cpp:2451
#9  0x00007fffdc4594e2 in cv::_OutputArray::create (this=0x7fffffffd598, _rows=31, _cols=1, mtype=0, i=-1, allowTransposed=false, fixedDepthMask=0)
    at /home/tr/opencv.lvv-git/modules/core/src/matrix.cpp:2266
#10 0x00007fffe263295a in cv::buildPyramid (_src=..., _dst=..., maxlevel=30, borderType=4)
    at /home/tr/opencv.lvv-git/modules/imgproc/src/pyramids.cpp:1506
#11 0x0000000000401b2c in main () at t.cc:7`

I somehow, in my previous message posted incorrect build config.  Here is my current build config:

` cmake  -D CMAKE_BUILD_TYPE=DEBUG -D CMAKE_INSTALL_PREFIX=/usr/local/opencv -D BUILD_TESTS=OFF -D WITH_CUDA=ON -D WITH_CUFFT=ON -D WITH_CUBLAS=ON -D CUDA_NVCC_FLAGS="-ccbin gcc-4.9" -D WITH_OPENCL=OFF -D WITH_OPENMP=ON -D WITH_VA_INTEL=ON -D WITH_VA=ON -D INSTALL_C_EXAMPLES=ON  -D WITH_TBB=ON -D WITH_IPP=ON -D WITH_V4L=ON -D WITH_OPENGL=ON  -DWITH_GDAL=ON -DWITH_XINE=ON -D BUILD_DOCS=ON  -D WITH_CSTRIPES=ON -D WITH_VTK=ON  -D ENABLE_AVX=ON -D ENABLE_POPCNT=ON -D ENABLE_SSE42=ON -D ENABLE_SSE41=ON -D ENABLE_SSSE3=ON ..`
