### ISSUE TITLE
ava.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil. Didn't find class "org.bytedeco.javacpp.avutil" on path: DexPathList

### ISSUE THREAD

**Issue by satyamub** [Itseez/opencv#6374]
Hi I am using this library for live streaming in android ... I am also using this  (https://github.com/Bilibili/ijkplayer) for playing RTMP. when I use them in different projects, there are working well like opencv which has ffmpeg is streaming the video and in another app which has this ijkplayer, I can see that stream, when I am trying to merge them, I found this below logcat

FATAL EXCEPTION: main
Process: com.satya.recordrtmp, PID: 26565
java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
at org.bytedeco.javacpp.Loader.load(Loader.java:415)
at org.bytedeco.javacpp.Loader.load(Loader.java:381)
at org.bytedeco.javacpp.avcodec$AVPacket.(avcodec.java:1650)
at org.bytedeco.javacv.FFmpegFrameRecorder.(FFmpegFrameRecorder.java:149)
at com.satya.recordrtmp.MainActivity.initRecorder(MainActivity.java:190)
at com.satya.recordrtmp.MainActivity.startRecording(MainActivity.java:205)
at com.satya.recordrtmp.MainActivity.onClick(MainActivity.java:501)
at android.view.View.performClick(View.java:4633)
at android.view.View$PerformClick.run(View.java:19270)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5602)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:251)
at org.bytedeco.javacpp.Loader.load(Loader.java:413)
            at org.bytedeco.javacpp.Loader.load(Loader.java:381)
            at org.bytedeco.javacpp.avcodec$AVPacket.(avcodec.java:1650)
            at org.bytedeco.javacv.FFmpegFrameRecorder.(FFmpegFrameRecorder.java:149)
            at com.satya.recordrtmp.MainActivity.initRecorder(MainActivity.java:190)
            at com.satya.recordrtmp.MainActivity.startRecording(MainActivity.java:205)
            at com.satya.recordrtmp.MainActivity.onClick(MainActivity.java:501)
            at android.view.View.performClick(View.java:4633)
            at android.view.View$PerformClick.run(View.java:19270)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avutil
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:251)
            at org.bytedeco.javacpp.Loader.load(Loader.java:413)
            at org.bytedeco.javacpp.Loader.load(Loader.java:381)
            at org.bytedeco.javacpp.avcodec$AVPacket.(avcodec.java:1650)
            at org.bytedeco.javacv.FFmpegFrameRecorder.(FFmpegFrameRecorder.java:149)
            at com.satya.recordrtmp.MainActivity.initRecorder(MainActivity.java:190)
            at com.satya.recordrtmp.MainActivity.startRecording(MainActivity.java:205)
            at com.satya.recordrtmp.MainActivity.onClick(MainActivity.java:501)
            at android.view.View.performClick(View.java:4633)
            at android.view.View$PerformClick.run(View.java:19270)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bytedeco.javacpp.avutil" on path: DexPathList[[zip file "/data/app/com.satya.recordrtmp-4.apk"],nativeLibraryDirectories=[/data/app-lib/com.satya.recordrtmp-4, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:251)
            at org.bytedeco.javacpp.Loader.load(Loader.java:413)
            at org.bytedeco.javacpp.Loader.load(Loader.java:381)
            at org.bytedeco.javacpp.avcodec$AVPacket.(avcodec.java:1650)
            at org.bytedeco.javacv.FFmpegFrameRecorder.(FFmpegFrameRecorder.java:149)
            at com.satya.recordrtmp.MainActivity.initRecorder(MainActivity.java:190)
            at com.satya.recordrtmp.MainActivity.startRecording(MainActivity.java:205)
            at com.satya.recordrtmp.MainActivity.onClick(MainActivity.java:501)
            at android.view.View.performClick(View.java:4633)
            at android.view.View$PerformClick.run(View.java:19270)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)

This is just happening if we want to use SDK 23 with app support 23.0.1 that does not mean below this, the error is not coming. The library also not working  in android 4.4.4(when used in separate project to test). I am thinking as both lib has FFMPEG and ijkplayer has that too, so its making this issue

**Comment by berak** [comment]
opencv does not maintain those libs.

can you please close this issue, and reopen it [here](https://github.com/bytedeco/javacv) or [here](https://github.com/bytedeco/javacpp) ?

**Comment by satyamub** [comment]
okay @berak ..I will close it. And further more.. i don't have to open them because, I have resolved the issue!!

**Comment by newstarbka** [comment]
@satyamub What did you do to resolve the issue ? Please share it for me. Thanks so much!
